nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: '@yarnpkg/plugin-interactive-tools'

# Latest working version is v2.3.1
# yarnPath: .yarn/releases/yarn-2.3.1.cjs

# After v2.4.0 hoisting is broken
yarnPath: .yarn/releases/yarn-2.4.0.cjs
